format_version: 10
pipelines:
  prod:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      uat:
        ignore_for_scheduling: false
        pipeline: uat
        stage: test
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"Deploy to Prod"'
                command: echo

    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '" Test in Prod pipeline"'
                command: echo
                run_if: passed
